# Document:
# http://simiki.org/docs/configuration.html

url: http://wiki.hanxi.info
title: Wiki · 涵曦
keywords: wiki, makrdown, linux, c, cpp, lua, hanxi
description: "Focus on C/C++, Linux, Lua, Game, and so on."
author:  涵曦
